### PR TITLE
Develop ads

### PR DESCRIPTION
**Pull request by a-stoddart**
I don't know how to get the files from main into my branch, is this the way?

### CODE REVIEW

**Comment by a-stoddart** [comment]
seemsa like pull just is about me putting my changes into main, which is the opposite of what I want, but I've tried everything else I can think of to fetch changes from main but am getting nowhere

**Comment by vincentpost** [comment]
Hi,

Indeed, a pull request is in the opposite direction. I am not sure what you have tried instead? I am guessing you might have made changes to the files in the main branch and then tried to get the new files by syncing in VSC. If there are conflicts then you’ll receive a warning that you need to resolve them. It’s impossible to give an specific advice without knowing exactly what you have tried and what messages you have been getting. Can you give more details?

Cheers,
Vincent

**Comment by a-stoddart** [comment]
Hi Vincent, 

So I pulled changes from the main branch in Git to my main branch in VS, which worked fine. As soon as I go into my branch, I can't seem to pull anything- I can't see how to pull things from main into my branch? I tried merging branches, but then it wants to merge my branch files with the main branch instead of just pulling the new files into my branch. The merge thing essentially has a list of "merge changes" (ie files I already had and was editing in my branch) and then a list of "staged changes" (ie the files I want to bring into my branch)

**Comment by a-stoddart** [comment]
unless the merge changes list will just pull changes you've made to main into my branch?

**Comment by a-stoddart** [comment]
Update, trurns out it worked! It's still upset because it wanted to do the merges that I wrote about above, but I can at least do the homework so it's not a massive deal :)

**Comment by vincentpost** [comment]
Glad to hear that. I am currently travelling so I did not get all the details but at least it sounds as if you can move ahead. Perhaps we can sort out any remaining issues later…

**Pull request closed without merging**
